[package]
name = "spot_difference"
version = "0.1.0"
authors = ["Wai Pai Lee <pailee.wai@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.21.1"
rand = "0.6.5"

[[example]]
name = "ex1"
path = "example/ex1/main.rs"

[[example]]
name = "ex2"
path = "example/ex2/main.rs"
