name: Rust

on:
  push:
    branches:
        - master
        - develop
        - release/*
  pull_request:
    branches:
    - master
    - develop

jobs:
  build_stable:
    name: Stable Rust
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable]

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      
  build_nightly:
    name: Nightly Rust
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [nightly]

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@v1
    - name: Build
      continue-on-error: true
      run: cargo +nightly build --verbose
    - name: Run tests
      continue-on-error: true
      run: cargo +nightly test --verbose
