name: Rust

on:
  push:
    branches:
        - master
        - develop
        - release/*
  pull_request:
    branches:
    - master
    - develop

jobs:
  build_stable:
    name: Stable Rust
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      
  build_nightly:
    name: Nightly Rust
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      continue-on-error: true
    - name: Build
      run: cargo +nightly build --verbose
    - name: Run tests
      run: cargo +nightly test --verbose
